version: "3.2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
      - /client/node_modules
    restart: always
    container_name: auction_client
    networks:
      - auction-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - 8001:80
    volumes:
      - ./server/:/var/www/symfony/
    restart: always
    container_name: auction_server
    networks:
      - auction-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - auction-mysql:/var/lib/mysql
    restart: always
    container_name: auction_mysql
    networks:
      - auction-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auction_mysql

  adminer:
    image: adminer
    ports:
      - 9001:8080
    restart: always
    container_name: auction_adminer
    networks:
      - auction-network

volumes:
  auction-mysql:

networks:
  auction-network:
