version: "3.2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
      - /client/node_modules/
    restart: always
    container_name: auction_client
    networks:
      auction-network:
        ipv4_address: 172.16.238.11

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - 9000:9000
    volumes:
      - ./server/:/var/www/symfony/
    restart: always
    container_name: auction_php
    networks:
      auction-network:
        ipv4_address: 172.16.238.12
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./server/:/var/www/symfony/
    restart: always
    container_name: auction_nginx
    networks:
      auction-network:
        ipv4_address: 172.16.238.13
    depends_on:
      - mysql

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./websocket/:/var/www/websocket/
      - /var/www/websocket/vendor/
    restart: always
    container_name: auction_websocket
    networks:
      auction-network:
        ipv4_address: 172.16.238.14
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.24
    ports:
      - 3306:3306
    volumes:
      - auction-mysql:/var/lib/mysql
    restart: always
    container_name: auction_mysql
    networks:
      auction-network:
        ipv4_address: 172.16.238.15
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auction_mysql

  adminer:
    image: adminer
    ports:
      - 9001:8080
    restart: always
    container_name: auction_adminer
    networks:
      auction-network:
        ipv4_address: 172.16.238.16

volumes:
  auction-mysql:

networks:
  auction-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
